### ISSUE TITLE
Freebox injoignable lorsqu'elle est éteinte

### ISSUE THREAD

**Issue by mysther** [betonniere/freeteuse#16]
Salut !

Depuis quelques mois, il est souvent nécessaire que je redémarre le player en coupant son alimentation.

J'ai regardé dans la partie "gestion de l'alimentation" et aucun réglage ne concerne le wifi. La box n'est pas connecté en wifi d'ailleurs mais par câble ethernet directement.

J'ai modifié le réglage du bouton d'alimentation de "mise en veille" à "extinction". La box n'est plus joignable directement après après avoir appuyé sur le bouton d'extinction.
On peut supposer qu'il y a un problème là.

L'application ne permet pas un wake-on-lan ?

**Comment by betonniere** [comment]
Salut, 


La box ne pourra pas se rallumer avec l'appli si la freebox est configurée pour s'éteindre complètement avec la touche Marche/Arrêt. 
Il faut impérativement revenir sur l'autre option. 
Pour le wake-on-lan ce ticket (https://dev.freebox.fr/bugs/task/16096) semble malheureusement confirmer que cela n'est pas possible. 

----- Mail original -----

De: "mysther" ***@***.***> 
À: "betonniere/freeteuse" ***@***.***> 
Cc: "Subscribed" ***@***.***> 
Envoyé: Mardi 7 Septembre 2021 19:21:41 
Objet: [betonniere/freeteuse] Freebox injoignable lorsqu'elle est éteinte (#16) 



Salut ! 
Depuis quelques mois, il est souvent nécessaire que je redémarre le player en coupant son alimentation. 
J'ai regardé dans la partie "gestion de l'alimentation" et aucun réglage ne concerne le wifi. La box n'est pas connecté en wifi d'ailleurs mais par câble ethernet directement. 
J'ai modifié le réglage du bouton d'alimentation de "mise en veille" à "extinction". La box n'est plus joignable directement après après avoir appuyé sur le bouton d'extinction. 
On peut supposer qu'il y a un problème là. 
L'application ne permet pas un wake-on-lan ? 
— 
You are receiving this because you are subscribed to this thread. 
Reply to this email directly, view it on GitHub , or unsubscribe . 
Triage notifications on the go with GitHub Mobile for iOS or Android .

**Comment by mysther** [comment]
Effectivement, je ne l'ai pas précisé, mais j'ai activé l'option uniquement pour mettre en évidence le problème !
Merci de la réponse rapide, j'ai des soucis sur deux box différentes, je pensais qu'il s'agissait d'un problème nouveau (pas forcément).
